#! /bin/sh

# xrdb ~/.Xresources

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          0
bspc config window_gap			  8
# bspc config left_padding		 		  	8
# bspc config right_padding				  	8
# bspc config bottom_padding			  	0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_modifier      mod1
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner

# Specific settings per app
bspc rule -r \*:\*
bspc rule -a Plank layer=above manage=on border=off
bscp node -f {west,south,north,east,next,prev}
bspc rule -a TelegramDesktop desktop='^6' follow=on
bspc rule -a discord desktop='^6' follow=on
bspc rule -a Subl desktop='^7' follow=on
bspc rule -a MusikCube desktop='^0' follow=on
bspc rule -a zoom desktop='^5' follow=on focus=on
bspc rule -a qBittorrent desktop='^7' state=floating center=true rectangle=1376x625+0+0 focus=on
bspc rule -a Nitrogen desktop='^1' state=floating center=true rectangle=1376x625+0+0 focus=on

# Border
# bspc config focused_border_color        "#000000"
# bspc config normal_border_color         "#ececec"
# bspc config active_border_color         "#000000"

# App settings

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
# nitrogen --restore &
variety &
# feh --bg-fill ~/.config/bspwm/img/14.* &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# Picom
picom -CGb --experimental-backend --config ~/.config/picom.conf &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Hides mouse when typing
xbanish &

# Keyboard
setxkbmap -option grp:win_space_toggle us,ru &

# Touchpad
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Tapping Drag Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput libinput Scroll Method Enabled" 1, 0, 0
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Disable While Typing Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Accel Speed" 0.6
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Scrolling Pixel Distance" 20
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Accel Profile Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Middle Emulation Enabled" 1

# Autostart applications
sh $HOME/.config/bspwm/scripts/autostart.sh &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
