#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock calendar uptime music github \
					reddit facebook youtube weather apps cava mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--tr" ]]; then
	close_dash && tor-browser &
	
elif [[ "$1" == "--xv" ]]; then
	close_dash && ${cmd} "https://mail.google.com" &
		
elif [[ "$1" == "--xn" ]]; then
	close_dash && ${cmd} "https://mail.google.com" &
		
elif [[ "$1" == "--" ]]; then
	close_dash && ${cmd} "https://mail.google.com" &
		
elif [[ "$1" == "--" ]]; then
	close_dash && ${cmd} "https://mail.google.com" &
		
elif [[ "$1" == "--" ]]; then
	close_dash && ${cmd} "https://mail.google.com" &
fi
