#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors settings
if [[ $(xrandr -q | grep "HDMI-A-0 connected" | cut -d ' ' -f1) ]]; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --right-of eDP

    bspc monitor ^1 -d I II III IV V VI VII VIII IX
    bspc monitor ^2 -d X

else

    bspc monitor -d I II III IV V VI VII VIII IX X

fi

bspc config remove_disabled_monitors 	  true
bspc config remove_unplugged_monitors 	  true
bspc config merge_overlapping_monitors    true
bspc wm --adopt-orphans

bspc config border_width                  6
bspc config window_gap                    6
bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config paddingless_monocle 	      true
bspc config gapless_monocle               true
bspc config single_monocle                false
bspc config pointer_follows_focus         true
bspc config focus_follows_pointer         true
bspc config click_to_focus                false
bspc config focus_by_distance             true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config swallow_first_click   	      true
bspc config pointer_modifier      		  mod4
bspc config pointer_action1       		  move
bspc config pointer_action2       		  resize_side
bspc config pointer_action3               resize_corner
bspc config ignore_ewmh_focus             true

# Border
bspc config focused_border_color        "#000000"
bspc config normal_border_color         "#ececec"
bspc config active_border_color         "#000000"

# Specific settings per app
bspc rule -r \*:\*
bspc rule -a "*:floating" state=floating rectangle=1200x800+720+240
bscp node -f {west,south,north,east,next,prev}
bspc rule -a plank layer=above manage=on border=off focus=off
bspc rule -a cairo-dock layer=above manage=on border=off focus=off
bspc rule -a copyq state=floating center=true focus=on

declare -a settings=(MEGAsync Lxappearance Lxtask Lxrandr Arandr \
Nm-connection-editor Pavucontrol:pavucontrol Blueberry.py)
for i in ${settings[@]}; do
bspc rule -a $i desktop='^1' state=floating center=true follow=on focus=on; done

declare -a code=(GParted Nitrogen Variety Timeshift-gtk)
for i in ${code[@]}; do
bspc rule -a $i desktop='^1' state=floating center=true rectangle=1376x725+0+0 focus=on follow=on; done

declare -a code=(qutebrowser chromium Google-chrome)
for i in ${code[@]}; do
bspc rule -a $i desktop='^2' follow=on focus=on; done

declare -a code=(Thunar Koreader)
for i in ${code[@]}; do
bspc rule -a $i desktop='^3' follow=on focus=on; done

declare -a code=(LibreWolf KeePassXC VeraCrypt tor-browser qBittorrent)
for i in ${code[@]}; do
bspc rule -a $i desktop='^4' follow=on focus=on; done

declare -a code=(TelegramDesktop)
for i in ${code[@]}; do
bspc rule -a $i desktop='^5' state=floating follow=off focus=off; done

declare -a code=(Zoom Skype discord)
for i in ${code[@]}; do
bspc rule -a $i desktop='^5' center=on follow=on border=off focus=on; done

declare -a code=(obsidian)
for i in ${code[@]}; do
bspc rule -a $i desktop='^6' follow=on focus=on; done

declare -a code=(Subl Koreader)
for i in ${code[@]}; do
bspc rule -a $i desktop='^7' state=floating center=true rectangle=1376x825+0+0 follow=on focus=on; done

declare -a code=(Code code-oss jetbrains-phpstorm)
for i in ${code[@]}; do
bspc rule -a $i desktop='^8' follow=on focus=on; done

declare -a code=(Virt-manager Upscayl figma-linux Gimp-2.10 Kuro)
for i in ${code[@]}; do
bspc rule -a $i desktop='^9' state=floating center=true rectangle=1476x925+0+0 focus=on follow=on; done

# declare -a code=('*:ncmpcpp', '*:cmus', '*:emusikcube', '*:cava')
# for i in ${code[@]}; do
# bspc rule -a $i desktop='^10' follow=off focus=off; done

# Bar
~/.config/polybar/launch.sh &

# Eww bar
if [[ `pidof eww` ]]; then
    pkill eww
fi
eww daemon &

# Notifications
if [[ `pidof dunst` ]]; then
    pkill dunst
fi
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Picom
killall -q picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom -CGb --config ~/.config/picom.conf &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Wallpaper
feh --bg-scale --randomize --no-fehbg ~/Pictures/Wallpapers/*

# Yellow colors
#while pgrep -u $UID -x redshift >/dev/null; do sleep 1; done
#redshift -c ~/.config/redshift/redshift.conf
#redshift -l 49:36 -t 6600:3800 -m randr &

# Cursor
xsetroot -cursor_name left_ptr &

# Hide mouse when typing
xbanish &

# Auto-hide the mouse cursor when inactive
unclutter &

# Keyboard
setxkbmap -option grp:win_space_toggle us,ru &

# Touchpad
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Tapping Drag Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput libinput Scroll Method Enabled" 1, 0, 0
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Disable While Typing Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Accel Speed" 0.6
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Scrolling Pixel Distance" 20
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Accel Profile Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Middle Emulation Enabled" 1

# Java Applications
wmname LG3D

# Include external_rules
bspc config external_rules_command ~/.config/bspwm/external_rules

# Start scripts
for i in "$HOME"/.config/bspwm/scripts/*.sh; do
    {
        eval "$i" &
    }
done

 # Comand to show app name
 # xprop | grep WM_CLASS
